version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - ./data/postgres-dev:/var/lib/postgresql/
    environment:
      POSTGRES_DB: nauka
      POSTGRES_USER: kuba
      POSTGRES_PASSWORD: kuba2024

